import 'package:clinic/features/auth/%20domain/repositories/Login_repositorie.dart';
import 'package:clinic/features/auth/%20domain/usecases/login_usecases.dart';
import 'package:clinic/features/auth/data/datasources/login_remote_date_source.dart';
import 'package:clinic/features/auth/data/repositories/login_repositories.dart';
import 'package:clinic/features/clinic/%20domain/repositories/ClinicRepositorie.dart';
import 'package:clinic/features/clinic/%20domain/usecases/add_clinic_today.dart';
import 'package:clinic/features/clinic/%20domain/usecases/get_all_clinic_today.dart';
import 'package:clinic/features/clinic/%20domain/usecases/update_clinic_data.dart';
import 'package:clinic/features/clinic/data/datasources/clinic_remote_data_source.dart';
import 'package:clinic/features/clinic/data/repositories/clinic_repositories.dart';
import 'package:clinic/features/doctor/%20domain/usecases/get_all_doctors.dart';
import 'package:clinic/features/fees/%20domain/usecases/get_fees_of_day.dart';
import 'package:clinic/features/fees/%20domain/usecases/get_fees_of_month.dart';
import 'package:clinic/features/nurce/%20domain/usecases/add_Nurse.dart';
import 'package:clinic/features/sick/%20domain/repositories/Sick_repositorie.dart';
import 'package:clinic/features/sick/%20domain/usecases/add%20_sick.dart';
import 'package:clinic/features/sick/%20domain/usecases/get_all_sicks.dart';
import 'package:clinic/features/sick/%20domain/usecases/get_sicks_based_on_user.dart';
import 'package:clinic/features/sick/%20domain/usecases/update_sick.dart';
import 'package:clinic/features/sick/%20domain/usecases/update_sick_as_entered.dart';
import 'package:clinic/features/sick/data/datasources/sick_remote_data_source.dart';
import 'package:clinic/features/sick/presentation/bloc/add_sick_bloc.dart';
import 'package:clinic/features/user/domain/usecases/add_user.dart';
import 'package:clinic/features/user/domain/usecases/edit_user.dart';
import 'package:clinic/features/visitor/%20domain/repositories/Visitor_repositorie.dart';
import 'package:clinic/features/visitor/%20domain/usecases/get_all_visitor_today.dart';
import 'package:clinic/features/visitor/%20domain/usecases/update_visitor_today.dart';
import 'package:clinic/features/visitor/data/datasources/visitor_remote_data_source.dart';
import 'package:clinic/features/visitor/presentation/bloc/add_update_visitor/add_update_visitor_bloc.dart';
import 'package:clinic/features/visitor/presentation/bloc/visitor/visitor_bloc.dart';
import 'package:get_it/get_it.dart';
import 'package:http/http.dart' as http;
import 'package:internet_connection_checker/internet_connection_checker.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../features/auth/presentation/bloc/bottom_cubit.dart';
import '../../features/auth/presentation/bloc/check_box_cubit.dart';
import '../../features/auth/presentation/bloc/eyes_cubit.dart';
import '../network/network_info.dart';
import '../../features/auth/presentation/bloc/login/login_bloc.dart';
import '../../features/clinic/presentation/bloc/actions_clinic_bloc.dart';
import '../../features/doctor/ domain/repositories/DoctorRepository.dart';
import '../../features/doctor/ domain/usecases/add_doctor.dart';
import '../../features/doctor/data/datasources/doctor_remote_data_source.dart';
import '../../features/doctor/data/repositories/doctor_repositories.dart';
import '../../features/doctor/presentation/bloc/doctor_bloc.dart';
import '../../features/fees/ domain/repositories/FeedRepository.dart';
import '../../features/fees/ domain/usecases/add_fees.dart';
import '../../features/fees/ domain/usecases/fees_delete.dart';
import '../../features/fees/ domain/usecases/update_fees.dart';
import '../../features/fees/data/datasources/fees_remote_data_source.dart';
import '../../features/fees/data/repositories/fees_repositories.dart';
import '../../features/fees/presentation/bloc/Fees_bloc.dart';
import '../../features/nurce/ domain/repositories/NurseRepository.dart';
import '../../features/nurce/ domain/usecases/get_all_Nurse.dart';
import '../../features/nurce/data/datasources/Nurse_remote_data_source.dart';
import '../../features/nurce/data/repositories/Nurse_repositories.dart';
import '../../features/nurce/presentation/bloc/Nurse_bloc.dart';
import '../../features/sick/ domain/usecases/add_sick_report.dart';
import '../../features/sick/data/repositories/sick_repositories.dart';
import '../../features/user/data/datasources/user_remote_data_source.dart';
import '../../features/user/data/repositories/user_repositories.dart';
import '../../features/user/domain/repositories/user_repositorie.dart';
import '../../features/user/presentation/bloc/user_bloc.dart';
import '../../features/visitor/ domain/usecases/add_visitor_today.dart';
import '../../features/visitor/data/repositories/visitor_repositories.dart';

part 'injection_import.dart';
